### ISSUE TITLE
DBR.jar Not Found

### ISSUE THREAD

**Issue by hemalzora** [kumarpuneet75/Online-Food-Ordering#1]
Please help me out bro

**Comment by kumarpuneet75** [comment]
there will be a jar file in build folder add that libraries in netbeans

**Comment by kumarpuneet75** [comment]
Online-Food-Ordering/project/Online Food Ordering/build/web/WEB-INF/lib
goto this there are two jar files 
add those in libraries in netbeans

**Comment by hemalzora** [comment]
ok done with but no database file

**Comment by kumarpuneet75** [comment]
i will put the dump file in few minutes

**Comment by hemalzora** [comment]
thanks
